_BASE_: "../../../DoG-RCNN-FPN-V2.yaml"
MODEL:
  WEIGHTS: "checkpoints/voc/faster_rcnn/faster_rcnn_R_101_DoG_FPN_V2_base3/model_reset_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 20
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_2007_trainval_all3_1shot',)
  TEST: ('voc_2007_test_all3',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.005
  STEPS: (3500,)
  MAX_ITER: 4000
  CHECKPOINT_PERIOD: 10000
  WARMUP_ITERS: 0
OUTPUT_DIR: "checkpoints/voc/faster_rcnn/faster_rcnn_R_101_DoG_FPN_V2_ft_normalized_all3_1shot_randnovel_0.005lr"